services:
  web:
    build: .
    container_name: vibe-web
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:16
    container_name: vibe-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
